### ISSUE TITLE
Problem while following the tutorial, involving perslay.utils

### ISSUE THREAD

**Issue by EdouardEPFL** [martinroyer/atol#2]
Hello,

While following the tutorial, and running the command "from atol.utils import compute_tda_for_graphs"

I obtain the following error: 

--------------------

ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_24964/1785446465.py in <module>
----> 1 from atol.utils import compute_tda_for_graphs

<frozen zipimport> in load_module(self, fullname)

~\anaconda3\lib\site-packages\atol-1.1.0-py3.9.egg\atol\utils.py in <module>
     23 from sklearn.cluster import MiniBatchKMeans
     24 
---> 25 from perslay.utils import apply_graph_extended_persistence, get_base_simplex
     26 from .atol import Atol
     27 

ModuleNotFoundError: No module named 'perslay.utils

---------------------
I want to report that my perslay is well installed. I also checked that in the master folder of perslay there is no file named "utils". Maybe it was the case in one of the older version and so this is not adapted anymore (just wondering) ?

Thanks for any kind of help

**Comment by martinroyer** [comment]
Hi Edouard,

Yes it is the case that perslay used to have those utils and it was reworked so this package relies on an older version of perslay. So your problem is with the package indeed - I cannot fix it at the moment but you can still use Atol if you have a running version of gudhi : https://gudhi.inria.fr/python/latest/representations.html

**Comment by EdouardEPFL** [comment]
Thank you very much for this fast answer. Yes, I have a running version of gudhi so I guess I'll manage with that one.

**Comment by martinroyer** [comment]
This is fixed now, even though there is nothing new in this package compared to using gudhi's : https://gudhi.inria.fr/python/latest/representations.html
